### ISSUE TITLE
Описание и помощь в установке

### ISSUE THREAD

**Issue by esliklientovnet** [64j/1c_exchange#1]
Добрый день. Подскажите есть ли более подробное описание модуля? Как устанавливается, как настраивается, какие возможности?

**Comment by 64j** [comment]
Устанавливается как и все модули, перекидывается в папку modules, создаётся модуль из шаблона, далее устанавливается по кнопке установить модуль, впрочем как и все модули, ничего особенного, стандартная установка.
Далее в настройках заполняются поля


На стороне 1С настраивается обмен с веб-сайтом,  выгрузка одного классификатора, в один пакет, что и когда выгружать, соединение с сайтом (логин и пароль).

Выгружает категории, товары и картинки.

**Comment by esliklientovnet** [comment]
модуль для modx evo? А для modx revo есть пакет?

**Comment by 64j** [comment]
модуль для Evo, по Revo ничего сказать не могу

**Comment by esliklientovnet** [comment]
понятно, спасибо! А то из основного описания непонятно было для какого modx

**Comment by 64j** [comment]
Если так посмотреть на все репозитории, на гите, то у меня ни одного для Revo
